[package]
name = "mdview"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = "0.4.2"
tokio = { version = "1", features = ["full"] }
comrak = "0.47"
notify = "8.2.0"
chrono = "0.4"
serde_json = "1.0.145"
axum = "0.8.6"
tower-http = "0.6.6"
